import {cp,mkdir,rm,readFile,writeFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url),dist=new URL('dist/',root);
await rm(dist,{recursive:true,force:true});await mkdir(dist,{recursive:true});
for(const name of ['index.html','style.css','src'])await cp(new URL(name,root),new URL(name,dist),{recursive:true});
console.log('Build complete: dist/');
const order=['card','deck','pay-table','joker-rule','hand-evaluator','double-down','game-state','sound','ui'];
const sources=await Promise.all(order.map(name=>readFile(new URL(`src/${name}.js`,root),'utf8')));
const bundled=sources.map(source=>source.replace(/^import .*;\r?\n/gm,'').replace(/\bexport (?=(const|class|function)\b)/g,'')).join('\n');
const html=await readFile(new URL('index.html',root),'utf8');
const css=await readFile(new URL('style.css',root),'utf8');
await writeFile(new URL('PLAY.html',root),html.replace('<link rel="stylesheet" href="./style.css">',`<style>${css}</style>`).replace('<script type="module" src="./src/ui.js"></script>',()=>`<script>\n${bundled}\n</script>`));
console.log('Standalone complete: PLAY.html (double-click to play, no server required)');
